server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: contract-service
          uri: lb://contract
          predicates:
            - Path=/api/contracts/**  # pas de StripPrefix

        - id: user-service
          uri: lb://user
          predicates:
            - Path=/api/users/**

        - id: payment-service
          uri: lb://payment
          predicates:
            - Path=/api/payments/**

        - id: notifications-service
          uri: lb://notifications
          predicates:
            - Path=/api/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/assurance_vie/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
