server:
  port: 8086

spring:
  application:
    name: ml-service
  datasource:
    url: jdbc:postgresql://localhost:5432/DW_Assurance
    username: postgres
    password: 191jMT1019MB..
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuration ML
ml:
  models:
    path: classpath:ml_models/
    prediction:
      model-file: logistic_model.joblib
      scaler-file: scaler.joblib
    clustering:
      model-file: kmeans_model.joblib
      scaler-file: clustering_scaler.joblib
  python:
    executable: python
    timeout: 30000
