server:
  port: 8085

spring:
  application:
    name: notifications
  mail:
    host: smtp.gmail.com
    port: 587
    username: medjoymdd@gmail.com
    password: sgkjvzwvolqagauz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/assurance_vie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
